### PR TITLE
Fix concurrent queues not to require default constructor from T

### LINKED ISSUE #885: concurrent_queue does not work when the object only has constructor with arguments
The problem:

```c++
#include <oneapi/tbb.h>
#include <oneapi/tbb/concurrent_queue.h>

class A
{
public:
    A(int a, int b) { }
};

int main(){
    oneapi::tbb::concurrent_queue<A> q1;
}
```
Compiler output
```
g++ -I repos/oneTBB/include -L repos/oneTBB/build/gnu_11.2_cxx11_64_relwithdebinfo main.cpp -ltbb -o main
In file included from repos/oneTBB/include/oneapi/tbb.h:42,
                 from main.cpp:1:
repos/oneTBB/include/oneapi/tbb/concurrent_queue.h: In instantiation of ‘void tbb::detail::d2::concurrent_queue<T, Allocator>::clear() [with T = A; Allocator = tbb::detail::d1::cache_aligned_allocator<A>]’:
repos/oneTBB/include/oneapi/tbb/concurrent_queue.h:111:9:   required from ‘tbb::detail::d2::concurrent_queue<T, Allocator>::~concurrent_queue() [with T = A; Allocator = tbb::detail::d1::cache_aligned_allocator<A>]’
main.cpp:11:38:   required from here
repos/oneTBB/include/oneapi/tbb/concurrent_queue.h:152:15: error: no matching function for call to ‘A::A()’
  152 |             T value;
      |               ^~~~~
main.cpp:7:5: note: candidate: ‘A::A(int, int)’
    7 |     A(int a, int b) { }
      |     ^
main.cpp:7:5: note:   candidate expects 2 arguments, 0 provided
main.cpp:4:7: note: candidate: ‘constexpr A::A(const A&)’
    4 | class A
      |       ^
main.cpp:4:7: note:   candidate expects 1 argument, 0 provided
main.cpp:4:7: note: candidate: ‘constexpr A::A(A&&)’
main.cpp:4:7: note:   candidate expects 1 argument, 0 provided
make: *** [Makefile:5: all] Error 1
```

The problem is cause by the function clear of concurrent_queue (oneTBB/include/oneapi/tbb/concurrent_queue.h:152) that instantiates an object to to be popped and clear the queue.

```c++
bool try_pop( T& result ) {
    return internal_try_pop(&result);
}

void clear() {
    while (!empty()) {
        T value;
        try_pop(value);
    }
}
```

Is it possible to use void* so that we can use concurrent_queue in these cases?

```c++
void clear() {
    while (!empty()) {
        void *value = malloc(sizeof(T));
        internal_try_pop(value);
        free(value);
    }
}
```

If that is ok, I can submit a PR.

### PR DESCRIPTION
**Pull request by kboyarinov**
### Description 
Fix the issue with `concurrent_queue` and `concurrent_bounded_queue` classes that required the default constructor of T to be present for `clear()` method and hence the destructor.

Fixes #885 

- [ ] - git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/oneapi-src/oneTBB/blob/master/CONTRIBUTING.md#pull-requests) for details)_

### Type of change

_Choose one or multiple, leave empty if none of the other choices apply_

_Add a respective label(s) to PR if you have permissions_

- [x] bug fix - _change that fixes an issue_
- [ ] new feature - _change that adds functionality_
- [ ] tests - _change in tests_
- [ ] infrastructure - _change in infrastructure and CI_
- [ ] documentation - _documentation update_

### Tests

- [x] added - _required for new features and some bug fixes_
- [ ] not needed

### Documentation

- [ ] updated in # - _add PR number_
- [ ] needs to be updated
- [x] not needed

### Breaks backward compatibility
- [ ] Yes
- [x] No
- [ ] Unknown

### Notify the following users
_List users with `@` to send notifications_

### CODE REVIEW

File: test/tbb/test_concurrent_queue.cpp [hunk 1]
```diff
@@ -199,3 +199,96 @@ TEST_CASE("Test exception in allocation") {
...
+        CHECK(element_counter == elements_count);
+        CHECK(default_container.empty());
+    }
+}
+
+//! \brief \ref regression \ref error_guessing
+TEST_CASE("Test with minimalistic object type") {
+    test_with_minimalistic_objects<oneapi::tbb::concurrent_queue>();
+    test_with_minimalistic_objects<oneapi::tbb::concurrent_bounded_queue>();
+}
```
Comment (pavelkumbrasev) [inline test/tbb/test_concurrent_queue.cpp:294]: Missed empty line

File: test/tbb/test_concurrent_queue.cpp [hunk 2]
```diff
@@ -199,3 +199,96 @@ TEST_CASE("Test exception in allocation") {
...
+            CHECK(default_container.try_pop(result));
+            ++element_counter;
+        }
+
+        CHECK(element_counter == elements_count);
+        CHECK(default_container.empty());
+    }
+}
+
+//! \brief \ref regression \ref error_guessing
```
Comment (pavelkumbrasev) [inline test/tbb/test_concurrent_queue.cpp:290]: It looks like requirement test (may be interface?), please consider move test to conformance

File: test/tbb/test_concurrent_queue.cpp [hunk 3]
```diff
@@ -199,3 +199,96 @@ TEST_CASE("Test exception in allocation") {
...
+    MinimalisticObject& operator=(const MinimalisticObject&) = delete;
+
+    std::size_t get_obj() const { return underlying_obj; }
+
+protected:
+    std::size_t underlying_obj;
+    friend struct MoveAssignableMinimalisticObject;
+};
+
+constexpr std::size_t MinimalisticObject::default_obj;
```
Comment (pavelkumbrasev) [inline test/tbb/test_concurrent_queue.cpp:221]: static constexpr variables can be initialized inside class, so you don't need move initialization outside class, am I right?

File: test/tbb/test_concurrent_queue.cpp [hunk 4]
```diff
@@ -199,3 +199,96 @@ TEST_CASE("Test exception in allocation") {
...
+
+        // Refill again
+        for (std::size_t i = 0; i < elements_count; ++i) {
+            default_container.emplace(MinimalisticObject::flag{});
+        }
+
+        MoveAssignableMinimalisticObject result(MinimalisticObject::flag{});
+
+        std::size_t element_counter = 0;
+        while(!default_container.empty()) {
```
Comment (pavelkumbrasev) [inline test/tbb/test_concurrent_queue.cpp:280]:
```suggestion
        while (!default_container.empty()) {
```

File: include/oneapi/tbb/detail/_concurrent_queue_base.h [hunk 5]
```diff
@@ -329,12 +332,21 @@ class micro_queue {
...
+    // Assign the item for regular pop operation
+    void select_pop_operation( void* dst, padded_page& src, size_type index, /*do_assign = */std::true_type ) {
+        __TBB_ASSERT(dst, "Incorrect destination for assign operation during pop");
         auto& from = src[index];
         destroyer d(from);
         *static_cast<T*>(dst) = std::move(from);
     }
 
+    // No assign for pop while clearing the queue
+    void select_pop_operation( void* dst, padded_page& src, size_type index, /*do_assign = */std::false_type ) {
```
Comment (pavelkumbrasev) [inline include/oneapi/tbb/detail/_concurrent_queue_base.h:344]:
```suggestion
    void select_pop_operation( void*, padded_page& src, size_type index, /*do_assign = */std::false_type ) {
```

File: include/oneapi/tbb/detail/_concurrent_queue_base.h [hunk 6]
```diff
@@ -189,7 +192,7 @@ class micro_queue {
                 k + queue_rep_type::n_queue, index == items_per_page - 1 ? p : nullptr );
             if (p->mask.load(std::memory_order_relaxed) & (std::uintptr_t(1) << index)) {
                 success = true;
-                assign_and_destroy_item( dst, *p, index );
+                select_pop_operation(dst, *p, index, do_assign);
```
Comment (pavelkumbrasev) [inline include/oneapi/tbb/detail/_concurrent_queue_base.h:195]: The function name doesn't correspond with actions inside function. What do you think about `pop_element`?

File: test/tbb/test_concurrent_queue.cpp (hunk 2 above)
Comment (kboyarinov) [reply test/tbb/test_concurrent_queue.cpp]: Moved to conformance test

File: test/tbb/test_concurrent_queue.cpp (hunk 3 above)
Comment (kboyarinov) [reply test/tbb/test_concurrent_queue.cpp]: If I correctly understood [this](https://stackoverflow.com/questions/8016780/undefined-reference-to-static-constexpr-char) 
we still need to provide definition for static constexpr variable outside of the class until C++17. 
My compiler generates a link-time error if I remove this line. Some compilers don't.
I have reworked this place because it does not strictly required

File: include/oneapi/tbb/detail/_concurrent_queue_base.h (hunk 5 above)
Comment (kboyarinov) [reply include/oneapi/tbb/detail/_concurrent_queue_base.h]: Irrelevant for the newest version of the patch

File: include/oneapi/tbb/detail/_concurrent_queue_base.h (hunk 6 above)
Comment (kboyarinov) [reply include/oneapi/tbb/detail/_concurrent_queue_base.h]: Irrelevant for the newest version of the patch

File: include/oneapi/tbb/detail/_concurrent_queue_base.h [hunk 7]
```diff
@@ -288,24 +288,34 @@ class micro_queue {
...
+    void clear(queue_allocator_type& allocator, padded_page* new_head = nullptr, padded_page* new_tail = nullptr) {
+        padded_page* curr_page = get_head_page();
+        size_type index = (head_counter.load(std::memory_order_relaxed) / queue_rep_type::n_queue) % items_per_page;
         page_allocator_type page_allocator(allocator);
 
-        while (curr_page) {
-            for (; index != items_per_page - 1; ++index) {
-                curr_page->operator[](index).~value_type();
+        while (curr_page && is_valid_page(curr_page)) {
+            while(index != items_per_page) {
```
Comment (pavelkumbrasev) [inline include/oneapi/tbb/detail/_concurrent_queue_base.h:297]:
```suggestion
            while (index != items_per_page) {
```

File: test/tbb/test_concurrent_queue.cpp [hunk 8]
```diff
@@ -199,3 +200,50 @@ TEST_CASE("Test exception in allocation") {
 }
 
 #endif // TBB_USE_EXCEPTIONS
+
+struct TrackableItem {
```
Comment (pavelkumbrasev) [inline test/tbb/test_concurrent_queue.cpp:204]: Could you please add new test that will test amount of constructed and destroyed items and test it with dtor and clear directly?

Comment (kboyarinov) [reply test/tbb/test_concurrent_queue.cpp:204]: Added dtor testing into the test with TrackableItem

**Review by pavelkumbrasev — APPROVED** [review]

**Review by pavelkumbrasev — APPROVED** [review]
