### PR TITLE
Deallocate object with based on actual type

### LINKED ISSUE #639: Assertion m_private_counter >= 0 failed (located in the destroy function, line in file: 141)
When using flow graph, the following assert failed with the following stderr output:

**Assertion m_private_counter >= 0 failed (located in the destroy function, line in file: 141)
Detailed description: Private counter may not be less than 0**

in the destroy function:

Call Stack:
image

_raise 0x000014a314b6637f
abort 0x000014a314b50db5
tbb::detail::r1::assertion_failure_impl assert_impl.h:56
operator() assert_impl.h:73
tbb::detail::d0::run_initializer<tbb::detail::r1::assertion_failure(char const*, int, char const*, char const*)::<lambda()> >(const struct {...} &, std::atomic<tbb::detail::d0::do_once_state> &) _utils.h:288
tbb::detail::d0::atomic_do_once<tbb::detail::r1::assertion_failure(char const*, int, char const*, char const*)::<lambda()> >(const struct {...} &, std::atomic<tbb::detail::d0::do_once_state> &) _utils.h:277
tbb::detail::r1::assertion_failure assert_impl.h:73
tbb::detail::r1::small_object_pool_impl::destroy small_object_pool.cpp:141
tbb::detail::r1::thread_data::~thread_data thread_data.h:120
tbb::detail::r1::governor::auto_terminate governor.cpp:221
tbb::detail::r1::market::cleanup market.cpp:611
tbb::detail::r1::rml::private_worker::run private_server.cpp:283
tbb::detail::r1::rml::private_worker::thread_routine private_server.cpp:221
start_thread 0x000014a3156a815a
clone 0x000014a314c2bdd3_

### PR DESCRIPTION
**Pull request by vlserov**
### Description 
`graph_task` deallocates another type than allocated. Provides actual type of object for `small_object_allocator` allocator.

Fixes #639

- [x] - git commit message contains appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/oneapi-src/oneTBB/blob/master/CONTRIBUTING.md#pull-requests) for details)_

### Type of change

_Choose one or multiple, leave empty if none of the other choices apply_

_Add respective label(s) to PR if you have permissions_

- [x] bug fix - _change which fixes an issue_
- [ ] new feature - _change which adds functionality_
- [ ] tests - _change in tests_
- [ ] infrastructure - _change in infrastructure and CI_
- [ ] documentation - _documentation update_

### Tests

- [ ] added - _required for new features and for some bug fixes_
- [x] not needed

### Documentation

- [ ] updated in # - _add PR number_
- [ ] needs to be updated
- [x] not needed

### Breaks backward compatibility
- [ ] Yes
- [x] No
- [ ] Unknown

### Notify the following users
@alexey-katranov

### CODE REVIEW

File: include/oneapi/tbb/detail/_flow_graph_impl.h [hunk 1]
```diff
@@ -359,21 +361,23 @@ class graph : no_copy, public graph_proxy {
 
 };  // class graph
 
+template<typename DerivedType>
 inline void graph_task::destruct_and_deallocate(const execution_data& ed) {
     auto allocator = my_allocator;
     // TODO: investigate if direct call of derived destructor gives any benefits.
     this->~graph_task();
-    allocator.deallocate(this, ed);
+    allocator.deallocate(static_cast<DerivedType*>(this), ed);
```
Comment (aleksei-fedotov) [inline include/oneapi/tbb/detail/_flow_graph_impl.h:369]: As far as I understand, the root cause of the issue is the automatic upcast of the `this` pointer to `graph_task` during the call to function template `allocator.deallocate()`.

Can we introduce an overload to `deallocate` function such as:
```cpp
    void deallocate(void* ptr, size_t size, const execution_data& ed);
```
to have:
```suggestion
    allocator.deallocate(this, sizeof(this), ed);
```
instead? 

This way allows us avoiding introduction of one more template parameter.

Comment (alexey-katranov) [reply include/oneapi/tbb/detail/_flow_graph_impl.h:369]: You cannot remove `static_cast` to the derived type because it is not guaranteed (in a general case) that the derived object has the same address as the parent object.

As for one more templated parameter, `sizeof(this)` in the parent class code is `sizeof` of the base class, in other words, `sizeof(this) != sizeof(static_cast<Derived*>(this))`. (C++ does not have reflection (yet?), i.e. we cannot get size information of the real object from the pointer to the parent object)

File: include/oneapi/tbb/detail/_flow_graph_impl.h [hunk 2]
```diff
@@ -359,21 +361,23 @@ class graph : no_copy, public graph_proxy {
...
-    destruct_and_deallocate(ed);
+    destruct_and_deallocate<DerivedType>(ed);
     g.release_wait();
 }
 
 inline task* graph_task::cancel(execution_data& ed) {
-    finalize(ed);
+    finalize<graph_task>(ed);
     return nullptr;
 }
```
Comment (alexey-katranov) [inline include/oneapi/tbb/detail/_flow_graph_impl.h:382]: Do we really need to override `cancel` in the `graph_task` now?

**Comment by alexey-katranov** [comment]
Why test is not needed? It is a bug fix and #639 contains reproducer.

File: include/oneapi/tbb/detail/_flow_graph_impl.h (hunk 1 above)
Comment (aleksei-fedotov) [reply include/oneapi/tbb/detail/_flow_graph_impl.h:369]: Yeah. I agree.

**Comment by phprus** [comment]
Do you have any updates?

**Comment by alexey-katranov** [comment]
> Do you have any updates?

@vlserov is on vacation, if the issue is urgent, we can try to reprioritize the task to some else?

**Comment by phprus** [comment]
@alexey-katranov, No this issue is not urgent for me. No need to change priorities.

File: include/oneapi/tbb/detail/_flow_graph_impl.h (hunk 2 above)
Comment (vlserov) [reply include/oneapi/tbb/detail/_flow_graph_impl.h]: Removed

File: include/oneapi/tbb/detail/_flow_graph_impl.h [hunk 3]
```diff
@@ -359,24 +360,21 @@ class graph : no_copy, public graph_proxy {
 
 };  // class graph
 
+template<typename DerivedType>
 inline void graph_task::destruct_and_deallocate(const execution_data& ed) {
     auto allocator = my_allocator;
     // TODO: investigate if direct call of derived destructor gives any benefits.
     this->~graph_task();
```
Comment (alexey-katranov) [inline include/oneapi/tbb/detail/_flow_graph_impl.h:367]: Maybe we will resolve the TODO? Check that all derived are final (does it make sense to mark them as `final`)? Or you can address it in a separate PR.
```suggestion
    this->DerivedType::~graph_task();
```

**Review by alexey-katranov — APPROVED** [review]
