### PR TITLE
Fix control variable initialization

### LINKED ISSUE #1341: Global task_schedule_observer leads to error on WASM and static lib x86
The following program:

```C++
#include <tbb/task_scheduler_observer.h>

class dummy_observer final : public tbb::task_scheduler_observer {
 public:
  dummy_observer() : tbb::task_scheduler_observer() {
    observe(true);  // activates the observer
  }

  void on_scheduler_entry(bool worker) override {}

  void on_scheduler_exit(bool worker) override {}
};

dummy_observer global_observer;

int main(int argc, char** argv) { return 0; }
```

When compiled with `em++` version 3.1.56 and run with node 19.9.0 yields:

```
/home/brian/Dev/cpp/tinystan/test.js:147
      throw ex;
      ^

RuntimeError: table index is out of bounds
    at test.wasm.tbb::detail::r1::threading_control::create_threading_control() (wasm://wasm/test.wasm-00c65a2a:wasm-function[846]:0x213be)
    at test.wasm.tbb::detail::r1::threading_control::register_public_reference() (wasm://wasm/test.wasm-00c65a2a:wasm-function[848]:0x21a6f)
    at test.wasm.tbb::detail::r1::governor::init_external_thread() (wasm://wasm/test.wasm-00c65a2a:wasm-function[485]:0xcfb4)
    at test.wasm.tbb::detail::r1::observe(tbb::detail::d1::task_scheduler_observer&, bool) (wasm://wasm/test.wasm-00c65a2a:wasm-function[481]:0xc700)
    at test.wasm.tbb::detail::d1::task_scheduler_observer::observe(bool) (wasm://wasm/test.wasm-00c65a2a:wasm-function[35]:0x119a)
    at test.wasm.dummy_observer::dummy_observer() (wasm://wasm/test.wasm-00c65a2a:wasm-function[32]:0xfe1)
    at test.wasm.__cxx_global_var_init (wasm://wasm/test.wasm-00c65a2a:wasm-function[31]:0xf36)
    at test.wasm._GLOBAL__sub_I_test.cpp (wasm://wasm/test.wasm-00c65a2a:wasm-function[56]:0x1848)
    at test.wasm.__wasm_call_ctors (wasm://wasm/test.wasm-00c65a2a:wasm-function[24]:0xe60)
    at callRuntimeCallbacks (/home/brian/Dev/cpp/tinystan/test.js:1519:26)

Node.js v19.9.0
```

### PR DESCRIPTION
**Pull request by SoilRos**
### Description 
Fixes initialization order bug stated in https://github.com/oneapi-src/oneTBB/issues/1341#issuecomment-2054095330

Fixes #1341

- [x] - git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/oneapi-src/oneTBB/blob/master/CONTRIBUTING.md#pull-requests) for details)_

### Type of change

_Choose one or multiple, leave empty if none of the other choices apply_

_Add a respective label(s) to PR if you have permissions_

- [x] bug fix - _change that fixes an issue_
- [ ] new feature - _change that adds functionality_
- [ ] tests - _change in tests_
- [ ] infrastructure - _change in infrastructure and CI_
- [ ] documentation - _documentation update_

### Tests

- [ ] added - _required for new features and some bug fixes_
- [x] not needed

### Documentation

- [ ] updated in # - _add PR number_
- [ ] needs to be updated
- [x] not needed

### Breaks backward compatibility
- [ ] Yes
- [x] No
- [ ] Unknown

### Notify the following users
@pavelkumbrasev

### CODE REVIEW

File: src/tbb/global_control.cpp [hunk 1]
```diff
@@ -139,13 +141,20 @@ class alignas(max_nfs_size) lifetime_control : public control_storage {
     }
 };
 
-static allowed_parallelism_control allowed_parallelism_ctl;
-static stack_size_control stack_size_ctl;
-static terminate_on_exception_control terminate_on_exception_ctl;
-static lifetime_control lifetime_ctl;
-static control_storage *controls[] = {&allowed_parallelism_ctl, &stack_size_ctl, &terminate_on_exception_ctl, &lifetime_ctl};
+static std::array<std::unique_ptr<control_storage>, 4> controls;
+static std::once_flag control_storage_flag;
```
Comment (kboyarinov) [inline src/tbb/global_control.cpp:145]: We have discussed the solution briefly within the team and it seems like it can result in more undefined behavior since `std::unique_ptr` and `std::once_flag` are not trivial structures and it can be unsafe to access them before initialization (in particular if `global_control_init()` would be called before constructing the `controls` and `control_storage_flag`.

We propose to have global static pointer to the storage containing all required global control variables and dynamically allocate it inside `governor::acquire_resources()` (which would be called during the first access to TBB) and deallocate inside `governor::release_resources ()`.
@pavelkumbrasev, feel free to add if I missed something.

What do you think about the proposed change?

Comment (SoilRos) [reply src/tbb/global_control.cpp:145]: I am _very_ unfamiliar with TBB internal code. I suspected that this solution may introduce more initialization problems as you pointed out, but I did not know where TBB initialized and destroyed things... so `unique_ptr` was the "easy" answer. With your hint we can give it a try on the `governor::[acquire|release]_resources` functions.

**Comment by SoilRos** [comment]
Previous commit fails due to C++14 compatibility on `new` alignment. Now this should hopefully be fixed.

File: src/tbb/global_control.cpp [hunk 2]
```diff
@@ -149,17 +152,20 @@ static control_storage_instance* control_storage_instance_ptr = nullptr;
 static control_storage *controls[4] = {nullptr, nullptr, nullptr, nullptr};
 
 void global_control_acquire() {
-    control_storage_instance_ptr = new control_storage_instance{};
+    auto ptr = aligned_alloc(max_nfs_size, sizeof(control_storage_instance));
```
Comment (phprus) [inline src/tbb/global_control.cpp:155]: MSVC does not support ``aligned_alloc``/``free``. Use ``_aligned_malloc`` and ``_aligned_free`` instead.

Comment (kboyarinov) [reply src/tbb/global_control.cpp:155]: I suggest to use special functions: `cache_aligned_allocate()` and `cache_aligned_deallocate()`

File: src/tbb/global_control.cpp [hunk 3]
```diff
@@ -139,11 +142,31 @@ class alignas(max_nfs_size) lifetime_control : public control_storage {
...
+    controls[2] = &control_storage_instance_ptr->terminate_on_exception_ctl;
+    controls[3] = &control_storage_instance_ptr->lifetime_ctl;
+}
+
+void global_control_release() {
+    for (auto& ptr : controls) {
+        ptr = nullptr;
+    }
+    control_storage_instance_ptr->~control_storage_instance();
+    free(std::exchange(control_storage_instance_ptr, nullptr));
```
Comment (pavelkumbrasev) [inline src/tbb/global_control.cpp:168]: `std::exchange` is not available in C++11

File: src/tbb/global_control.cpp [hunk 4]
```diff
@@ -139,11 +142,31 @@ class alignas(max_nfs_size) lifetime_control : public control_storage {
...
-static lifetime_control lifetime_ctl;
-static control_storage *controls[] = {&allowed_parallelism_ctl, &stack_size_ctl, &terminate_on_exception_ctl, &lifetime_ctl};
+struct alignas(max_nfs_size) control_storage_instance {
+    allowed_parallelism_control     allowed_parallelism_ctl;
+    stack_size_control              stack_size_ctl;
+    terminate_on_exception_control  terminate_on_exception_ctl;
+    lifetime_control                lifetime_ctl;
+};
+static control_storage_instance* control_storage_instance_ptr = nullptr;
+static control_storage *controls[4] = {nullptr, nullptr, nullptr, nullptr};
```
Comment (pavelkumbrasev) [inline src/tbb/global_control.cpp:152]: Do we really need an extra variable + extra class? Can we just use pointer to array?

Comment (SoilRos) [reply src/tbb/global_control.cpp:152]: It’s not really needed, I was trying to follow @kboyarinov’s instructions but I guess I understood them wrongly. So you meant that each control variable is allocated separately, right?

One argument for the struct is that it only needs one allocation so data is more compact.   With individual allocations you have to hard-code the derived class twice too anyways (construction/destruction). On the other hand, one can argue that the struct is slightly less maintainable, so I’d understand if you still prefer one allocation per class.

Comment (SoilRos) [reply src/tbb/global_control.cpp:152]: Nvm, I just realized that every class sits in it’s own cache line so the “compact” argument doesn’t really hold…

File: src/tbb/global_control.cpp [hunk 5]
```diff
@@ -27,6 +28,7 @@
 #include "misc.h"
 
 #include <atomic>
+#include <new>
```
Comment (pavelkumbrasev) [inline src/tbb/global_control.cpp:31]: Do we really need this?

File: src/tbb/global_control.cpp [hunk 6]
```diff
@@ -139,11 +141,22 @@ class alignas(max_nfs_size) lifetime_control : public control_storage {
     }
 };
 
-static allowed_parallelism_control allowed_parallelism_ctl;
-static stack_size_control stack_size_ctl;
-static terminate_on_exception_control terminate_on_exception_ctl;
-static lifetime_control lifetime_ctl;
-static control_storage *controls[] = {&allowed_parallelism_ctl, &stack_size_ctl, &terminate_on_exception_ctl, &lifetime_ctl};
+static control_storage *controls[4] = {nullptr, nullptr, nullptr, nullptr};
```
Comment (pavelkumbrasev) [inline src/tbb/global_control.cpp:144]:
```suggestion
static control_storage* controls[] = {nullptr, nullptr, nullptr, nullptr};
```

File: src/tbb/global_control.cpp [hunk 7]
```diff
@@ -17,6 +17,7 @@
 #include "oneapi/tbb/detail/_config.h"
```
Comment (kboyarinov) [inline src/tbb/global_control.cpp:17]: Please update the last copyright year to 2024 for both files to satisfy the copyright check.

**Review by pavelkumbrasev — COMMENTED** [review]
Overall the patch looks good!

**Review by kboyarinov — COMMENTED** [review]
Excluding the copyright comment - LGTM

**Comment by SoilRos** [comment]
I addressed your reviews and squashed the commits, Thanks!

I was thinking that we may add a test for this with a global observer as presented in the original issue #1341. I just do not know where to put it. Do you have a hint where it can go? Or do you think it's not necessary?

**Comment by pavelkumbrasev** [comment]
> I was thinking that we may add a test for this with a global observer as presented in the original issue #1341. I just do not know where to put it. Do you have a hint where it can go? Or do you think it's not necessary?

As I understand we cannot reproduce this failure without compiling TBB statically.  I don't know if we previously added separate tests for a specific platform.

**Comment by SoilRos** [comment]
Alright, then this is ready from my side. I just amended my commit with the copyright comment (I hope it's correct). There is no changes in the code since the last CI run.

**Review by pavelkumbrasev — APPROVED** [review]

**Comment by pavelkumbrasev** [comment]
> Maybe add tests for static build?

It might make sense since WASM compile TBB statically. Do you want to contribute it ? 😄

**Review by kboyarinov — APPROVED** [review]
LGTM

**Comment by phprus** [comment]
> > Maybe add tests for static build?
> 
> It might make sense since WASM compile TBB statically. Do you want to contribute it ? 😄

PR: #1350
